services:
  nginx:
    image: nginx:latest
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro/"
      - "./config/nginx.conf:/etc/nginx/nginx.conf"
      - "./certs/dhparam.pem:/etc/nginx/certs/dhparam.pem" # Certificate generete by certs-create.sh script
#      - "./certs/fullchain.pem:/etc/nginx/certs/fullchain.pem" # Certificate generete by certs-create.sh script
#      - "./certs/privkey.pem:/etc/nginx/certs/privkey.pem" # Certificate generete by certs-create.sh script
      - ./letsencrypt/certbot/conf:/etc/letsencrypt # Certificate generete by Letsencrypt script
      - ./letsencrypt/certbot/www:/var/www/certbot # Certificate generete by Letsencrypt script
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      app-network:
        ipv4_address: 172.20.0.11
    restart: "always"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./letsencrypt/certbot/conf:/etc/letsencrypt
      - ./letsencrypt/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      app-network:
        ipv4_address: 172.20.0.12
    restart: always

networks:
  app-network:
    ipam:
      config:
        - subnet: 172.20.0.0/24
